# Dependencies
markdown: kramdown
pygments: true
#timezone: Asia/Shanghai
highlighter: rouge

permalink: pretty

# Site Info
title: "Phaeton:  "
tagline: 'A tiny DSL for DNN accelerator tensor expressions'

url: https://lijiansong.github.io/Phaeton
baseurl: /Phaeton

github:
  repo: https://github.com/lijiansong/Phaeton

encoding: utf-8

author:
  name: 'Json Lee'
  description: 'Phaeton is a domain specific language for machine learning tensor expressions with performance portability at different hardware platforms.'
  url: https://lijiansong.github.io/Phaeton

# Site configurations
paginate: 5
#gems:
#  - jekyll-paginate
version: 1.0.0
